language: python

python:
  - "2.7"

services:
  - redis-server

before_install:
  - sudo apt-get install daemontools

install:
  - pip install pip --upgrade
  - pip install -r requirements-dev.txt --allow-unverified pyPdf
  - pip install coveralls

before_script:
  - pep8 --exclude=migrations facile_backlog
  - pep8 tests

script:
  - PYTHONPATH=. make coverage

after_success:
  - coverage report
  - coveralls
