language: python

python:
  - "2.7"

before_install:
  - sudo apt-get install daemontools

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls

before_script:
  - pep8 --exclude=migrations facile_backlog
  - pep8 tests

script:
  - PYTHONPATH=. make coverage
  - coverage report -m

after_success:
  - coveralls
